var favorites = [];

var sides = [
  'Succotash',
  'Hush Puppies',
  'Hot Corn-Pone',
  'Doe Birds On Toast',
  'Snake Soup',
  'Hardtack',
  'Truffle Tots',
  'Boston Bacon And Beans',
  'Deviled Eggs',
  'Stewed Tomatoes',
  'Shrimp Summer Rolls',
  'Street Corn',
  'Buttermilk Biscuits',
  'Sardines',
  'Hot Hoe-Cake',
  'News And Gossip',
];

var mains = [
  'Potomac Shad, broiled',
  'Prairie Liens From Illinois',
  'Missouri Partridges, broiled',
  'Sheep-head & Croakers',
  'Baltimore Perch',
  'Fresh Tongue With Spinach',
  'Cornish Pasties',
  'Larded Quail',
  'New York East River Turtle',
  'Lake Trout From Tahoe',
  'Roast Corned Pork',
  'Cherry-Stone Clams',
  'Mississippi Black Bass ',
  'Roast Wild Woodcock',
  'Roast Beaver Tail',
  'Old Eel Pie',
  'Ducks Of Mutton',
  'Veal Fricandeau',
];

var desserts = [
  'Lemon Meringue Pie',
  'Banana Pudding',
  'Lady Fingers',
  'Hot Buckwheat Cakes',
  'Croissants',
  'Rum Jelly',
  'Tipsy Cake',
  'Whim Wham',
  'Macaroons',
  'Apple Puffs',
  'Queen Fritters',
  'Champagne Jelly',
  'Tart Tatin',
  'Eclairs',
  'Bread And Butter Pudding',
];
