var favorites = [];

var sides = [
  'Succotash',
  'Hush Puppies',
  'Hot Corn-Pone',
  'Doe Birds On Toast',
  'Snake Soup',
  'Boston Bacon And Beans',
  'Aspic de Foie Gras',
  'Truffle Tots',
  'Deviled Eggs',
  'Stewed Tomatoes',
  'News And Gossip',
  'Shrimp Summer Rolls',
  'Buttermilk Biscuits',
  'Sardines',
  'Hot Hoe-Cake',
];

var mains = [
  'Potomac Shad, broiled',
  'Prairie Liens From Illinois',
  'Missouri Partridges, broiled',
  'Cornish Pasties',
  'Sheep-head & Croakers',
  'Baltimore Perch',
  'Fresh Tongue With Spinach',
  'Larded Quail',
  'New York East River Turtle',
  'Lake Trout From Tahoe',
  'Roast Corned Pork',
  'Cherry-Stone Clams',
  'Roast Wild Woodcock',
  'Roast Beaver Tail',
  'Mississippi Black Bass ',
  'Old Eel Pie',
  'Ducks Of Mutton',
  'Veal Fricandeau',
];

var desserts = [
  'Lemon Meringue Pie',
  'Banana Pudding',
  'Lady Fingers',
  'Hot Buckwheat Cakes',
  'Rum Jelly',
  'Tipsy Cake',
  'Croissants',
  'Whim Wham',
  'A Fat Cigar',
  'Macaroons',
  'Apple Puffs',
  'Queen Fritters',
  'Champagne Jelly',
  'Tart Tatin',
  'Eclairs',
  'Bread And Butter Pudding',
];
